### ISSUE TITLE
I need Days, Hours, Minutes and Seconds. these are in separate div

### ISSUE THREAD

**Issue by ahirhasmukh** [matheushf/ng2-date-countdown#1]
I need Days, Hours, Minutes and Seconds. These are in separate div or any tag. If it is possible then please revert me
Please check attached screenshot. I want to do like that

![needto](https://user-images.githubusercontent.com/8941195/28300419-f8c5747c-6b9c-11e7-8b02-3417391cab3f.png)

I have faced some issue. 14 days left but when I have tried to separate then getting an issue.

Right now I am getting` <h1>14 Days 4 Hours 34 Minutes 27 Seconds</h1>` but
I want to `<h1>14 Days</h1> <h1>4 Hours</h1> <h1>34 Minutes</h1> <h1>27 Seconds</h1>`
It is possible?

![issue](https://user-images.githubusercontent.com/8941195/28300436-12a9ca6e-6b9d-11e7-9452-6330bda03f5c.png)

**Comment by matheushf** [comment]
Are you sure that you are using my component? ng2-date-countdown, and not another countdown? 
Because as you can see in [here](https://github.com/matheushf/ng2-date-countdown/blob/master/lib/countdown.html) I'm generating one div for each.

**Comment by Albejr** [comment]
It is interesting to separate the text elements (hour, minutes ..) and the digits (23, 59 ...), thus allowing different styles to be applied.
![image](https://user-images.githubusercontent.com/24717256/28502394-deb42446-6fc7-11e7-9a1c-da92a07d84e5.png)

using your component:
![image](https://user-images.githubusercontent.com/24717256/28502411-6318ce80-6fc8-11e7-9b56-cd6287382569.png)

**Comment by matheushf** [comment]
It's indeed better.  This week I'll make it and release, just have to do some stuff before.

**Comment by ahirhasmukh** [comment]
Thanks @matheushf

**Comment by matheushf** [comment]
I did the split from numbers and text, update it to try.

Cheers!
