### ISSUE TITLE
When dates comes do zero.

### ISSUE THREAD

**Issue by ronaldohoch** [matheushf/ng2-date-countdown#12]
Hello!
Awesome component, thank You a lot!

Is there a way to know when it get zero or negative time, to prevent this:

![image](https://user-images.githubusercontent.com/2287371/40588533-1f867ba6-61b5-11e8-8e89-cb84f600784a.png)

**Comment by matheushf** [comment]
Thanks! :) 
I've updated the component, now the counter will always display 0 instead of negative, and you can use it with the `(reached)` event:

```
<countdown 
(reached)="reached($event)" 
units="Month | Days | Hours | Minutes | Seconds"  
end="2018/05/28 12:08:50">
</countdown>
```

**Comment by ronaldohoch** [comment]
Great!
Will be available in NPM soon?

**Comment by matheushf** [comment]
It should be there already. Did you updated it? Version 1.0.1
