### ISSUE TITLE
How Configure Time Zone 

### ISSUE THREAD

**Issue by Txucishvili** [matheushf/ng2-date-countdown#13]
hi few days age i have created this issue but its been deleted...
i want to insert +4 time zone can you help me?

**Comment by matheushf** [comment]
Hey, I thought it was just a question. But what is happening? You set the date and it gets 4 hours less? 
What timezone are you using?

**Comment by hoermiller** [comment]
@Txucishvili 

The easiest way is to create a date object. You can set your timezone offset there, but it should also use the current timezone you are in. A good library is momentJS. For me this worked really well. I simply created a new date object and turned it into an isoString

**Comment by matheushf** [comment]
Thanks @hoermiller! 

I will close this issue then.
