### ISSUE TITLE
moduleId should be a string

### ISSUE THREAD

**Issue by hoermiller** [matheushf/ng2-date-countdown#14]
# My Environment 
```
cli packages: (/Users/jan-ole/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4 Build version 9F1027a 

Environment Variables:

    ANDROID_HOME : /Users/jan-ole/Library/Android/sdk

Misc:

    backend : pro
```

# What is the problem?
When adding this module to my project I got the following error message:
```Uncaught Error: moduleId should be a string in "CountDown". See https://goo.gl/wIDDiL for more information.```

# How to fix this
Simply add ```.toString()``` to the component declaration in ```component.ts``` (line 4).

**Comment by matheushf** [comment]
How are you importing or using it? Since this error wasn't reported yet, I don't believe it's just simple add `.toString()`.
Please post some part of your code.

**Comment by hoermiller** [comment]
Hey, thanks for the quick response.
First I installed the module via npm and then I added the module as described into my ```app.module.ts```

```
import { CountDown } from "ng2-date-countdown";

// Plugins
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

// Pages
import { MyApp } from './app.component';
import { SchedulePage, AuthPage, PostsPage, PostPage, TabsPage, RosterPage, TeamsPage, TeamPage } from '../pages/.';

// Providers
import { AfvdProvider, AuthProvider, WordpressProvider, SportspressProvider } from '../providers/.';

@NgModule({
  declarations: [
    MyApp,
    CountDown,
```

and the simply used the countdown component in my page view like this:

```
<countdown *ngIf="games && games.length > 0" units="Days | Hours | Minutes | Seconds" [text]="countdownText"  [end]="games[0].isoDate"></countdown>
```

when I keep the described line as is, I get an error. As soon as I transform the module id into a string everything works. Not sure if it's just an outdated dependency problem on my end.

**Comment by matheushf** [comment]
I've searched about it, and it happens that module.id is not even needed anymore, so I just removed it. Thanks for the issue. :)
