### ISSUE TITLE
showZeros not working or am I misunderstanding something

### ISSUE THREAD

**Issue by CatinhoCR** [matheushf/ng2-date-countdown#17]
I might be doing something wrong here but the showZeros property is not working for me.
How is it supposed to be set up? 

I tried doing it in the element selector's html as an attribute like
```<countdown units="Days" end="October 05, 2018" [showZeros]="true"></countdown>```

I tried with and without quotes and assigning it into the component as an object property but not sure what am I doing wrong. The error in the console says it's not a known property of the component.

**Comment by CatinhoCR** [comment]
Wasn't paying attention and am a little tired atm. To be used without the brackets like the units and end properties.

**Comment by CatinhoCR** [comment]
Al though it did show an additional "0" in a new ```.measurement``` ```<div>``` which I had to hide in the css because im a bit of a rush to figure it out by looking at the code.

**Comment by matheushf** [comment]
So, everything working?

**Comment by Thassya** [comment]
just for the record... it works when you put _showZero_ instead of _showZeros_
