### ISSUE TITLE
Build error with Angular 7

### ISSUE THREAD

**Issue by Albejr** [matheushf/ng2-date-countdown#18]
Will there be maintenance for new versions of the Angular?

`Module not found: Error: Can't resolve 'rxjs/Observable' in '\node_modules\ng2-date-countdown\node_modules\@angular\core\esm5'`

**Comment by matheushf** [comment]
Yes it will, I'll be fixing it today or tomorrow. Thanks for the issue!

**Comment by matheushf** [comment]
Updated
