### ISSUE TITLE
What the Bold? [feature request]

### ISSUE THREAD

**Issue by ghost** [matheushf/ng2-date-countdown#2]
Hi there,

this is not so much an issue as an idea for improvement, currently you are using `<b>` tags for the values, but it breaks a lot of fonts / styleguides, so every time I use your component, I have to manually take out the boldness. How about a) getting rid of the forced boldness all together or b) defining an @Input that can be used like `<countdown bold=false>` ?

Cheeerio! =)

**Comment by matheushf** [comment]
Hello,

Thanks for the tip! I don't remember why I used `<b>` in the first place, but I changed it to `<p>`, going to update.

Cheerss!
