### ISSUE TITLE
Make it able to build with Prod and AOT

### ISSUE THREAD

**Issue by matheushf** [matheushf/ng2-date-countdown#23]
Right now some people are reporting they are unable to compile it with Prod and AOT settings. 

That might have something to do with the way it's being packaged, decorators or something like that. For someone who already made an Angular Prod/AOT compatible package, it should be easy.

**Comment by gshokanov** [comment]
The problem is that the generated bundle is missing the required metadata for the AOT. The simplest solution is to migrate to `ng-packagr` from `gulp`. I'll do it.
