### ISSUE TITLE
Build error with Angular 5

### ISSUE THREAD

**Issue by Albejr** [matheushf/ng2-date-countdown#3]
When implementing ng2-date-countdown in an Angular 5 project, I get the following build error when running `ng serve`:

ERROR in ./node_modules/ng2-date-countdown/lib/countdown.ts
Module build failed: Error: C:\...\node_modules\ng2-date-countdown\lib\countdown.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\...\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:649:23)
    at plugin.done.then (C:\...\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/ng2-date-countdown/index.ts 6:9-35
 @ ./src/app/components/dashboard/dashboard.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.

![image](https://user-images.githubusercontent.com/24717256/34312557-26e0776e-e74c-11e7-8527-a526f76a80cb.png)

**Comment by matheushf** [comment]
Thanks for reporting, I will look into it

**Comment by matheushf** [comment]
The problem is that I wasn't compiling it before publishing, Angular 5.0 requires it. Try updating the component, it should work fine now
