### ISSUE TITLE
How to give a specific format to the countdown

### ISSUE THREAD

**Issue by ghizoulo** [matheushf/ng2-date-countdown#7]
Hello @matheushf , 
Thanks for this library, it is easy to use and it helps a lot
I have a little problem with it
For example, if I have in my countdown 
`1 days : 2 hours : 5 minutes : 5 secondes `
I want to display it like this
`01 days : 02 hours : 05 minutes : 05 secondes`

Please help me if there is a way to do it

**Comment by matheushf** [comment]
Oh, good point, I'll add that

**Comment by matheushf** [comment]
Done, use it with `[showZero]="true"` in the options

Thanks for using it!

**Comment by ghizoulo** [comment]
@matheushf Thanks for your reply and quick contribution
As I check the "**Usage**" bloc again, i am confused, should I use `units, end, text, showzero` with or without brackets ?

**Comment by matheushf** [comment]
Actually it can be with or without, I'll update the readme.md to show it with brackets

**Comment by matheushf** [comment]
If you are passing a variable or boolean, use it with brackets. And if it's just a string, use without brackets. It's an Angular thing actually. I'll update the docs
