### ISSUE TITLE
Support for events

### ISSUE THREAD

**Issue by ashe540** [matheushf/ng2-date-countdown#8]
Hey @matheushf, I was wondering if there are plans to support events for the countdown. There are cases when you would like to take some action on the UI when the countdown hits 0, for example. The ability to stop the countdown would be interesting as well, so that it does not display: `-1 days 23 hours 59 minutes 59 seconds` after hitting 0, and continue counting backwards.

Thanks!

**Comment by matheushf** [comment]
Oh, it's a good idea. I'll make it this week :)

**Comment by matheushf** [comment]
You can use it with the `(reached)` event:

```
<countdown 
(reached)="reached($event)" 
units="Month | Days | Hours | Minutes | Seconds"  
end="2018/05/28 12:08:50">
</countdown>
```
